# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'porta.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frente(object):
    def setupUi(self, frente):
        frente.setObjectName("frente")
        frente.resize(816, 577)
        frente.setMinimumSize(QtCore.QSize(816, 577))
        frente.setMaximumSize(QtCore.QSize(816, 577))
        self.frente1 = QtWidgets.QWidget(frente)
        self.frente1.setObjectName("frente1")
        self.background = QtWidgets.QLabel(self.frente1)
        self.background.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.background.setMinimumSize(QtCore.QSize(816, 577))
        self.background.setMaximumSize(QtCore.QSize(816, 577))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/png/FrenteCube.png"))
        self.background.setObjectName("background")
        self.porta = QtWidgets.QPushButton(self.frente1)
        self.porta.setGeometry(QtCore.QRect(190, 40, 251, 461))
        self.porta.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.porta.setText("")
        self.porta.setObjectName("porta")
        self.label = QtWidgets.QLabel(self.frente1)
        self.label.setGeometry(QtCore.QRect(10, 260, 50, 50))
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/setaE.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frente1)
        self.label_2.setGeometry(QtCore.QRect(760, 260, 50, 50))
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/png/setaD.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.esquerda = QtWidgets.QPushButton(self.frente1)
        self.esquerda.setGeometry(QtCore.QRect(0, 250, 71, 61))
        self.esquerda.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.esquerda.setText("")
        self.esquerda.setObjectName("esquerda")
        self.direira = QtWidgets.QPushButton(self.frente1)
        self.direira.setGeometry(QtCore.QRect(724, 250, 91, 71))
        self.direira.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.direira.setText("")
        self.direira.setObjectName("direira")
        frente.setCentralWidget(self.frente1)

        self.retranslateUi(frente)
        QtCore.QMetaObject.connectSlotsByName(frente)

    def retranslateUi(self, frente):
        _translate = QtCore.QCoreApplication.translate
        frente.setWindowTitle(_translate("frente", "MainWindow"))
import frente_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frente = QtWidgets.QMainWindow()
    ui = Ui_frente()
    ui.setupUi(frente)
    frente.show()
    sys.exit(app.exec_())
