# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mesa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mesa(object):
    def setupUi(self, mesa):
        mesa.setObjectName("mesa")
        mesa.resize(816, 577)
        mesa.setMinimumSize(QtCore.QSize(816, 577))
        mesa.setMaximumSize(QtCore.QSize(1000, 1000))
        self.mesa1 = QtWidgets.QWidget(mesa)
        self.mesa1.setMinimumSize(QtCore.QSize(816, 577))
        self.mesa1.setMaximumSize(QtCore.QSize(816, 577))
        self.mesa1.setObjectName("mesa1")
        self.label = QtWidgets.QLabel(self.mesa1)
        self.label.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setMaximumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/mesa.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.voltar = QtWidgets.QPushButton(self.mesa1)
        self.voltar.setGeometry(QtCore.QRect(350, 510, 120, 60))
        self.voltar.setMinimumSize(QtCore.QSize(120, 60))
        self.voltar.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.voltar.setObjectName("voltar")
        mesa.setCentralWidget(self.mesa1)

        self.retranslateUi(mesa)
        QtCore.QMetaObject.connectSlotsByName(mesa)

    def retranslateUi(self, mesa):
        _translate = QtCore.QCoreApplication.translate
        mesa.setWindowTitle(_translate("mesa", "MainWindow"))
        self.voltar.setText(_translate("mesa", "Voltar"))
import Sala_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mesa = QtWidgets.QMainWindow()
    ui = Ui_mesa()
    ui.setupUi(mesa)
    mesa.show()
    sys.exit(app.exec_())
