# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sala.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sala(object):
    def setupUi(self, sala):
        sala.setObjectName("sala")
        sala.resize(816, 577)
        sala.setMinimumSize(QtCore.QSize(816, 577))
        sala.setMaximumSize(QtCore.QSize(816, 577))
        self.sala1 = QtWidgets.QWidget(sala)
        self.sala1.setObjectName("sala1")
        self.label = QtWidgets.QLabel(self.sala1)
        self.label.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setMaximumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(":/png/SalaCube.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.sofa = QtWidgets.QPushButton(self.sala1)
        self.sofa.setGeometry(QtCore.QRect(180, 290, 561, 221))
        self.sofa.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.sofa.setText("")
        self.sofa.setObjectName("sofa")
        self.mesa = QtWidgets.QPushButton(self.sala1)
        self.mesa.setGeometry(QtCore.QRect(60, 280, 111, 91))
        self.mesa.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.mesa.setText("")
        self.mesa.setObjectName("mesa")
        self.quadro = QtWidgets.QPushButton(self.sala1)
        self.quadro.setGeometry(QtCore.QRect(390, 20, 211, 261))
        self.quadro.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.quadro.setText("")
        self.quadro.setObjectName("quadro")
        self.label_2 = QtWidgets.QLabel(self.sala1)
        self.label_2.setGeometry(QtCore.QRect(10, 260, 50, 50))
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/png/setaE.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.sala1)
        self.label_3.setGeometry(QtCore.QRect(760, 260, 50, 50))
        self.label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/png/setaD.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.esquerda = QtWidgets.QPushButton(self.sala1)
        self.esquerda.setGeometry(QtCore.QRect(0, 250, 61, 61))
        self.esquerda.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.esquerda.setText("")
        self.esquerda.setObjectName("esquerda")
        self.direita = QtWidgets.QPushButton(self.sala1)
        self.direita.setGeometry(QtCore.QRect(750, 250, 61, 71))
        self.direita.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.direita.setText("")
        self.direita.setObjectName("direita")
        sala.setCentralWidget(self.sala1)

        self.retranslateUi(sala)
        QtCore.QMetaObject.connectSlotsByName(sala)

    def retranslateUi(self, sala):
        _translate = QtCore.QCoreApplication.translate
        sala.setWindowTitle(_translate("sala", "MainWindow"))
import Sala_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sala = QtWidgets.QMainWindow()
    ui = Ui_sala()
    ui.setupUi(sala)
    sala.show()
    sys.exit(app.exec_())
