# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import ImagensCozinha_rc
import cozinha

class Ui_armario(object):
    def setupUi(self, armario):
        armario.setObjectName("armario")
        armario.resize(816, 600)
        armario.setMinimumSize(QtCore.QSize(816, 577))
        self.armario1 = QtWidgets.QWidget(armario)
        self.armario1.setObjectName("armario1")
        self.label = QtWidgets.QLabel(self.armario1)
        self.label.setGeometry(QtCore.QRect(0, 0, 821, 601))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/armario.png"))
        self.label.setScaledContents(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")

        self.voltar = QtWidgets.QPushButton(self.armario1)
        self.voltar.setGeometry(QtCore.QRect(350, 530, 120, 60))
        self.voltar.setMinimumSize(QtCore.QSize(120, 60))
        self.voltar.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.voltar.setObjectName("voltar")
        self.voltar.clicked.connect(self.armario_cozinha)
        armario.setCentralWidget(self.armario1)
        self.retranslateUi(armario)
        QtCore.QMetaObject.connectSlotsByName(armario)

    def retranslateUi(self, armario):
        _translate = QtCore.QCoreApplication.translate
        armario.setWindowTitle(_translate("armario", "MainWindow"))
        self.voltar.setText(_translate("armario", "Voltar"))


    def armario_cozinha(self):
        armario.close()
        cozinha.abrir_cozinha()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    armario = QtWidgets.QMainWindow()
    ui = Ui_armario()
    ui.setupUi(armario)
    armario.show()
    sys.exit(app.exec_())
