# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carta.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_carta(object):
    def setupUi(self, carta):
        carta.setObjectName("carta")
        carta.resize(816, 577)
        carta.setMinimumSize(QtCore.QSize(816, 577))
        carta.setMaximumSize(QtCore.QSize(816, 577))
        self.carta1 = QtWidgets.QWidget(carta)
        self.carta1.setMinimumSize(QtCore.QSize(816, 577))
        self.carta1.setMaximumSize(QtCore.QSize(816, 577))
        self.carta1.setObjectName("carta1")
        self.label_2 = QtWidgets.QLabel(self.carta1)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label_2.setMinimumSize(QtCore.QSize(816, 577))
        self.label_2.setMaximumSize(QtCore.QSize(816, 577))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/png/carta.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.voltar = QtWidgets.QPushButton(self.carta1)
        self.voltar.setGeometry(QtCore.QRect(350, 510, 120, 60))
        self.voltar.setMinimumSize(QtCore.QSize(120, 60))
        self.voltar.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.voltar.setObjectName("voltar")
        carta.setCentralWidget(self.carta1)

        self.retranslateUi(carta)
        QtCore.QMetaObject.connectSlotsByName(carta)

    def retranslateUi(self, carta):
        _translate = QtCore.QCoreApplication.translate
        carta.setWindowTitle(_translate("carta", "MainWindow"))
        self.voltar.setText(_translate("carta", "Voltar"))
import ImagensCozinha_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    carta = QtWidgets.QMainWindow()
    ui = Ui_carta()
    ui.setupUi(carta)
    carta.show()
    sys.exit(app.exec_())
