# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cozinha.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ImagensCozinha_rc


class Ui_cozinha(object):
    def setupUi(self, cozinha):
        cozinha.setObjectName("cozinha")
        cozinha.resize(816, 577)
        cozinha.setMinimumSize(QtCore.QSize(816, 577))
        cozinha.setMaximumSize(QtCore.QSize(816, 577))
        cozinha.setAutoFillBackground(False)
        cozinha.setStyleSheet("backgroung-img: url(imagens/Cozinha/CozinhaCube.png);")
        self.cozinha1 = QtWidgets.QWidget(cozinha)
        self.cozinha1.setObjectName("cozinha1")
        self.backgroung = QtWidgets.QLabel(self.cozinha1)
        self.backgroung.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.backgroung.setMinimumSize(QtCore.QSize(816, 577))
        self.backgroung.setMaximumSize(QtCore.QSize(816, 577))
        self.backgroung.setAutoFillBackground(False)
        self.backgroung.setText("")
        self.backgroung.setPixmap(QtGui.QPixmap(":/png/CozinhaCube.png"))
        self.backgroung.setScaledContents(True)
        self.backgroung.setWordWrap(False)
        self.backgroung.setObjectName("backgroung")
        self.geladeira = QtWidgets.QPushButton(self.cozinha1)
        self.geladeira.setGeometry(QtCore.QRect(260, 100, 191, 471))
        self.geladeira.setStyleSheet("background-color:rgba(0, 0, 0, 0);")
        self.geladeira.setText("")
        self.geladeira.setObjectName("geladeira")
        self.armario = QtWidgets.QPushButton(self.cozinha1)
        self.armario.setGeometry(QtCore.QRect(610, 10, 201, 261))
        self.armario.setStyleSheet("background-color:rgba(0, 0, 0, 0);")
        self.armario.setText("")
        self.armario.setObjectName("armario")
        self.pia = QtWidgets.QPushButton(self.cozinha1)
        self.pia.setGeometry(QtCore.QRect(0, 130, 231, 111))
        self.pia.setStyleSheet("background-color:rgba(0, 0, 0, 0);")
        self.pia.setText("")
        self.pia.setObjectName("pia")
        self.label = QtWidgets.QLabel(self.cozinha1)
        self.label.setGeometry(QtCore.QRect(10, 260, 50, 51))
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/setaE.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.cozinha1)
        self.label_2.setGeometry(QtCore.QRect(760, 270, 50, 50))
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/png/setaD.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.esquerda = QtWidgets.QPushButton(self.cozinha1)
        self.esquerda.setGeometry(QtCore.QRect(0, 250, 81, 61))
        self.esquerda.setStyleSheet("background-color:rgba(0, 0, 0, 0);")
        self.esquerda.setText("")
        self.esquerda.setObjectName("esquerda")
        self.direita = QtWidgets.QPushButton(self.cozinha1)
        self.direita.setGeometry(QtCore.QRect(750, 270, 61, 61))
        self.direita.setStyleSheet("background-color:rgba(0, 0, 0, 0);")
        self.direita.setText("")
        self.direita.setObjectName("direita")
        cozinha.setCentralWidget(self.cozinha1)

        self.retranslateUi(cozinha)
        QtCore.QMetaObject.connectSlotsByName(cozinha)

    def retranslateUi(self, cozinha):
        _translate = QtCore.QCoreApplication.translate
        cozinha.setWindowTitle(_translate("cozinha", "MainWindow"))



def abrir_cozinha():
    import sys
    import ImagensCozinha_rc
    app = QtWidgets.QApplication(sys.argv)
    cozinha = QtWidgets.QMainWindow()
    ui = Ui_cozinha()
    ui.setupUi(cozinha)
    cozinha.show()
    sys.exit(app.exec_())
