# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relogio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_relogio(object):
    def setupUi(self, relogio):
        relogio.setObjectName("relogio")
        relogio.resize(816, 577)
        relogio.setMinimumSize(QtCore.QSize(816, 577))
        relogio.setMaximumSize(QtCore.QSize(816, 577))
        self.relogio1 = QtWidgets.QWidget(relogio)
        self.relogio1.setObjectName("relogio1")
        self.label = QtWidgets.QLabel(self.relogio1)
        self.label.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setMaximumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/relogio.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.voltar = QtWidgets.QPushButton(self.relogio1)
        self.voltar.setGeometry(QtCore.QRect(350, 510, 120, 60))
        self.voltar.setMinimumSize(QtCore.QSize(120, 60))
        self.voltar.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.voltar.setObjectName("voltar")
        relogio.setCentralWidget(self.relogio1)

        self.retranslateUi(relogio)
        QtCore.QMetaObject.connectSlotsByName(relogio)

    def retranslateUi(self, relogio):
        _translate = QtCore.QCoreApplication.translate
        relogio.setWindowTitle(_translate("relogio", "MainWindow"))
        self.voltar.setText(_translate("relogio", "Voltar"))
import lazer_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    relogio = QtWidgets.QMainWindow()
    ui = Ui_relogio()
    ui.setupUi(relogio)
    relogio.show()
    sys.exit(app.exec_())
