# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teclado.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teclado(object):
    def setupUi(self, teclado):
        teclado.setObjectName("teclado")
        teclado.resize(816, 577)
        teclado.setMinimumSize(QtCore.QSize(816, 577))
        teclado.setMaximumSize(QtCore.QSize(816, 577))
        self.teclado1 = QtWidgets.QWidget(teclado)
        self.teclado1.setObjectName("teclado1")
        self.label = QtWidgets.QLabel(self.teclado1)
        self.label.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setMaximumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/escrever.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.voltar = QtWidgets.QPushButton(self.teclado1)
        self.voltar.setGeometry(QtCore.QRect(350, 510, 120, 60))
        self.voltar.setMinimumSize(QtCore.QSize(120, 60))
        self.voltar.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.voltar.setObjectName("voltar")
        teclado.setCentralWidget(self.teclado1)

        self.retranslateUi(teclado)
        QtCore.QMetaObject.connectSlotsByName(teclado)

    def retranslateUi(self, teclado):
        _translate = QtCore.QCoreApplication.translate
        teclado.setWindowTitle(_translate("teclado", "MainWindow"))
        self.voltar.setText(_translate("teclado", "Voltar"))
import lazer_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teclado = QtWidgets.QMainWindow()
    ui = Ui_teclado()
    ui.setupUi(teclado)
    teclado.show()
    sys.exit(app.exec_())
