# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tv(object):
    def setupUi(self, tv):
        tv.setObjectName("tv")
        tv.resize(816, 577)
        tv.setMinimumSize(QtCore.QSize(816, 577))
        tv.setMaximumSize(QtCore.QSize(816, 577))
        self.tv1 = QtWidgets.QWidget(tv)
        self.tv1.setObjectName("tv1")
        self.label = QtWidgets.QLabel(self.tv1)
        self.label.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setMaximumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/tv.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tv1)
        self.pushButton.setGeometry(QtCore.QRect(350, 510, 120, 60))
        self.pushButton.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.pushButton.setObjectName("pushButton")
        tv.setCentralWidget(self.tv1)

        self.retranslateUi(tv)
        QtCore.QMetaObject.connectSlotsByName(tv)

    def retranslateUi(self, tv):
        _translate = QtCore.QCoreApplication.translate
        tv.setWindowTitle(_translate("tv", "MainWindow"))
        self.pushButton.setText(_translate("tv", "Voltar"))
import lazer_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tv = QtWidgets.QMainWindow()
    ui = Ui_tv()
    ui.setupUi(tv)
    tv.show()
    sys.exit(app.exec_())
