# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quadro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quadro(object):
    def setupUi(self, quadro):
        quadro.setObjectName("quadro")
        quadro.setEnabled(True)
        quadro.resize(816, 577)
        quadro.setMinimumSize(QtCore.QSize(816, 577))
        quadro.setMaximumSize(QtCore.QSize(816, 577))
        self.quadro1 = QtWidgets.QWidget(quadro)
        self.quadro1.setObjectName("quadro1")
        self.label = QtWidgets.QLabel(self.quadro1)
        self.label.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setMaximumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/quadro.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.voltar = QtWidgets.QPushButton(self.quadro1)
        self.voltar.setGeometry(QtCore.QRect(350, 510, 120, 60))
        self.voltar.setMinimumSize(QtCore.QSize(120, 60))
        self.voltar.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.voltar.setObjectName("voltar")
        quadro.setCentralWidget(self.quadro1)

        self.retranslateUi(quadro)
        QtCore.QMetaObject.connectSlotsByName(quadro)

    def retranslateUi(self, quadro):
        _translate = QtCore.QCoreApplication.translate
        quadro.setWindowTitle(_translate("quadro", "MainWindow"))
        self.voltar.setText(_translate("quadro", "Voltar"))
import Sala_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quadro = QtWidgets.QMainWindow()
    ui = Ui_quadro()
    ui.setupUi(quadro)
    quadro.show()
    sys.exit(app.exec_())
