# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sofa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sofa(object):
    def setupUi(self, sofa):
        sofa.setObjectName("sofa")
        sofa.resize(816, 577)
        sofa.setMinimumSize(QtCore.QSize(816, 577))
        sofa.setMaximumSize(QtCore.QSize(816, 577))
        self.sofa1 = QtWidgets.QWidget(sofa)
        self.sofa1.setObjectName("sofa1")
        self.label = QtWidgets.QLabel(self.sofa1)
        self.label.setGeometry(QtCore.QRect(0, 0, 816, 577))
        self.label.setMinimumSize(QtCore.QSize(816, 577))
        self.label.setMaximumSize(QtCore.QSize(816, 577))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/sofa.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.voltar = QtWidgets.QPushButton(self.sofa1)
        self.voltar.setGeometry(QtCore.QRect(350, 10, 120, 60))
        self.voltar.setMinimumSize(QtCore.QSize(120, 60))
        self.voltar.setStyleSheet("border-radius: 1px;\n"
"background-color: rgba(0, 0, 0, 0.7);\n"
"color: grey;\n"
"font-size: 30px;")
        self.voltar.setObjectName("voltar")
        sofa.setCentralWidget(self.sofa1)

        self.retranslateUi(sofa)
        QtCore.QMetaObject.connectSlotsByName(sofa)

    def retranslateUi(self, sofa):
        _translate = QtCore.QCoreApplication.translate
        sofa.setWindowTitle(_translate("sofa", "MainWindow"))
        self.voltar.setText(_translate("sofa", "Voltar"))
import Sala_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sofa = QtWidgets.QMainWindow()
    ui = Ui_sofa()
    ui.setupUi(sofa)
    sofa.show()
    sys.exit(app.exec_())
